[workspace]
members = ["crates/*"]

[workspace.dependencies]
anyhow = "1.0.75"
argh = "0.1.12"
time = "0.3.30"
yansi = "0.5.1"
reqwest = "0.11.22"
serde = "1.0.193"
toml = "0.8.8"

[package]
name = "advent-bins"
version = "0.0.0"
edition = "2021"

[dependencies]
advent = { path = "crates/advent" }
itertools = "0.12.0"

[[bin]]
name = "202201"
path = "2022/01.rs"

[[bin]]
name = "202301"
path = "2023/01.rs"

[[bin]]
name = "202302"
path = "2023/02.rs"
